namespace DA.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addBranchEntity : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Branch",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        dbaAddress1 = c.String(),
                        dbaAddress2 = c.String(),
                        dbaAddress3 = c.String(),
                        City_Id = c.Int(nullable: false),
                        DBAName = c.String(),
                        areaMallCode = c.Int(),
                        payDelayDays = c.Int(),
                        dateClosed = c.DateTime(nullable: false),
                        closedreason = c.Int(),
                        owningMerchant = c.String(),
                        JCBAcceptorId = c.String(),
                        JCBSchemeClosereason = c.Int(),
                        JCBSchemeRevisionReason = c.Int(),
                        JCBRevisionRSN = c.Int(),
                        schemeAreaCode1 = c.Int(),
                        schemeAreaCode2 = c.Int(),
                        AMEXCardAcceptorId = c.String(),
                        AMEXActivationReason = c.Int(),
                        AMEXCanceledReason = c.Int(),
                        AMEXRoleCode = c.Int(),
                        AMEXRiskIND = c.String(),
                        AMEXKeyAcctIND = c.String(),
                        CUPCardAcceptorId = c.String(),
                        CUPTaxCode = c.Int(),
                        CUPTaxNumber = c.String(),
                        CUPTaxExemptExpiryDate = c.DateTime(nullable: false),
                        imprinterPlateName = c.String(),
                        imprinterPlateNumbers = c.String(),
                        imprinterAMEX = c.String(),
                        imprinterDC = c.String(),
                        imprinterJCB = c.String(),
                        imprinterOthers = c.String(),
                        principalName1 = c.String(),
                        principalName2 = c.String(),
                        principalName3 = c.String(),
                        principalName4 = c.String(),
                        principalName5 = c.String(),
                        adminContactperson = c.String(),
                        goodsServices = c.String(),
                        phoneNo = c.String(),
                        mobileNo = c.String(),
                        emailAddress = c.String(),
                        mailingAddress1 = c.String(),
                        withECR = c.Boolean(nullable: false),
                        merchantGrade = c.Int(),
                        serviceProvider = c.String(),
                        website = c.String(),
                        cardHolderData = c.Boolean(nullable: false),
                        cardHolderDataTobeStored = c.String(),
                        MCC_Id = c.Int(nullable: false),
                        branchCode = c.String(),
                        imprinterTotal = c.Int(),
                        dbaZipCode = c.Int(nullable: false),
                        regionCode = c.Int(),
                        checkDeliveryCode = c.Int(),
                        paymentMode = c.String(),
                        settlementAcctNo = c.String(),
                        merchantGroupCode = c.String(),
                        TIN = c.String(),
                        withTax = c.Boolean(),
                        cardPlan = c.Int(),
                        isActive = c.Boolean(),
                        isAffiliated = c.Boolean(),
                        dbaAddress4 = c.String(),
                        principalFirstName = c.String(),
                        principalLastName = c.String(),
                        principalMiddleName = c.String(),
                        mailingAddress2 = c.String(),
                        mailingAddress3 = c.String(),
                        mailingAddress4 = c.String(),
                        mailingCity = c.Int(nullable: false),
                        mailingAddressZipCode = c.Int(nullable: false),
                        dbaCity = c.Int(),
                        taxExemptFrom = c.DateTime(nullable: false),
                        taxExemptTo = c.DateTime(nullable: false),
                        taxExemptIssuedBy = c.Int(nullable: false),
                        registeredBusinessNo = c.String(),
                        DTIBusinessRegDate = c.DateTime(nullable: false),
                        SECRegDate = c.DateTime(nullable: false),
                        withAcquirer = c.Boolean(),
                        acquirerInstitutionName = c.String(),
                        ecrForInstallation = c.Boolean(nullable: false),
                        isSwipingCardWithoutInstalledECR = c.Boolean(nullable: false),
                        isSwipingCardWithInstalledECR = c.Boolean(nullable: false),
                        debitSettlementAcctNo = c.String(),
                        payeesName = c.String(),
                        emailAddressForReport = c.String(),
                        SOARecipients = c.String(),
                        SOAEmailAddress = c.String(),
                        reportDistributionperCompany = c.Boolean(nullable: false),
                        reportPerBranch = c.Boolean(nullable: false),
                        principalFbName = c.String(),
                        principalDateOfBirth = c.DateTime(nullable: false),
                        principalCivilStatus = c.Int(nullable: false),
                        principalPhoneNo = c.String(),
                        principalPermanentAddress = c.String(),
                        principalCity = c.Int(nullable: false),
                        principalZipCode = c.Int(nullable: false),
                        principalHomeOwnership = c.Int(nullable: false),
                        spouseAddress = c.String(),
                        spouseCity = c.Int(nullable: false),
                        spouseFirstName = c.String(),
                        spouseLastName = c.String(),
                        spouseMiddleName = c.String(),
                        spousePhoneNo = c.String(),
                        spouseZipCode = c.Int(nullable: false),
                        financialInstitution = c.String(),
                        accountFacility = c.String(),
                        acctLoanNo = c.String(),
                        loanTerm = c.String(),
                        noOfPos = c.Int(nullable: false),
                        discountDebitRate = c.Decimal(nullable: false, precision: 18, scale: 2),
                        storeId = c.String(),
                        reportPerCompanysBranch = c.String(),
                        ftpDir = c.String(),
                        genPayment = c.Boolean(nullable: false),
                        computeCWT = c.Boolean(nullable: false),
                        settlementPerBranch = c.Boolean(nullable: false),
                        customerNo = c.String(),
                        amexRating = c.Int(nullable: false),
                        bdoPayRating = c.Int(nullable: false),
                        bdoPaySegment = c.Int(nullable: false),
                        aoCode = c.String(),
                        feeAccount = c.String(),
                        forMoto = c.String(),
                        strategicMerchant = c.Int(nullable: false),
                        tranSource = c.Int(nullable: false),
                        holdOutAcctNo = c.String(),
                        holdOutAmount = c.String(),
                        remarks = c.String(),
                        preparedBy = c.String(),
                        preparedDate = c.DateTime(),
                        notedBy = c.String(),
                        notedDate = c.String(),
                        controlNo = c.String(),
                        smsSending = c.Boolean(),
                        withDependency = c.Boolean(),
                        custr = c.Boolean(),
                        postMaintReview = c.Boolean(),
                        postMaintReviewDate = c.DateTime(),
                        currentDate = c.DateTime(),
                        midCount = c.String(),
                        midDateTimeCreated = c.DateTime(),
                        tidCount = c.String(),
                        tidDateTimeCreated = c.DateTime(),
                        mdf = c.String(),
                        mdfChecker = c.String(),
                        mdfDateTimeChecked = c.DateTime(),
                        mdfMaker = c.String(),
                        mcId = c.Int(nullable: false),
                        debitMailingAddressCity = c.Int(nullable: false),
                        debitMailingAddressZipCode = c.Int(nullable: false),
                        sendBdo030114 = c.Int(nullable: false),
                        branch = c.String(),
                        tradeCustomerName = c.String(),
                        tradeContactNo = c.String(),
                        debitMerchantNo = c.String(),
                        isSingleProp = c.Boolean(),
                        isPartnershipCorp = c.Boolean(),
                        mdfDateTimeCreated = c.DateTime(),
                        legalName = c.String(),
                        Request_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Request", t => t.Request_Id)
                .Index(t => t.Request_Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Branch", "Request_Id", "dbo.Request");
            DropIndex("dbo.Branch", new[] { "Request_Id" });
            DropTable("dbo.Branch");
        }
    }
}
